services:
  postgresql:
    container_name: ixveria_infrastructure_db
    image: postgres:latest
    env_file:
      - path: "../../.env"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRES_NAME}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - ixveria_infrastructure

networks:
  ixveria_infrastructure:
    driver: bridge