services:
  postgresql:
    container_name: ixveria_infrastructure_db
    image: postgres:latest
    hostname: localhost
    ports:
    - "5432:5432"
    env_file: "../../.env"
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRES_NAME}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ixveria_infrastructure

networks:
  ixveria_infrastructure:
    driver: bridge

volumes:
  postgresql:
    driver: local